name = "research-programs"
version = "0.1.0"
license = "MIT"
author = "Thales Freitas Macedo"
maintainer = "Thales Freitas Macedo"
description = "Programs developed for physics simulations"

[build]
auto-executables = true
auto-tests = false
auto-examples = false
link = ["lapack", "blas"]

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[library]
source-dir = "src"

[dependencies]
stdlib = "*"

[[test]]
name = "test-lapack-blas"
source-dir = "tests"
main = "test_lapack_blas.f90"