name = "research-programs"
version = "0.1.0"
license = "MIT"
author = "Thales Freitas Macedo"
maintainer = "Thales Freitas Macedo"
description = "Programs developed for physics simulations"

[build]
auto-executables = true
auto-tests = false
auto-examples = false
link = ["lapack", "blas"]

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[features]
debug.gfortran.flags = "-Og -Wall -Wextra -g -fcheck=all -fbacktrace"
debug.ifort.flags = "-O0 -warn all -traceback -check all -diag-disable=10448"

release.gfortran.flags = "-O2"
release.ifort.flags = "-O2 -diag-disable=10448"

[profiles]
debug = ["debug"]
release = ["release"]

[library]
source-dir = "src"

[dependencies]
blas = "*"
stdlib = "*"

[[test]]
name = "test-lapack-blas"
source-dir = "tests"
main = "test_lapack_blas.f90"